-- из официального реестра IANA (Internet Assigned Numbers Authority)
-- Вставляем самые часто используемые порты
INSERT INTO well_known_ports (port, name) VALUES
  (20, 'ftp-data'),
  (21, 'ftp'),
  (22, 'ssh'),
  (23, 'telnet'),
  (25, 'smtp'),
  (53, 'dns'),
  (80, 'http'),
  (110, 'pop3'),
  (123, 'ntp'),
  (135, 'msrpc'),
  (139, 'netbios-ssn'),
  (143, 'imap'),
  (443, 'https'),
  (445, 'microsoft-ds'),
  (993, 'imaps'),
  (995, 'pop3s'),
  (1723, 'pptp'),
  (3306, 'mysql'),
  (3389, 'rdp'),
  (5432, 'postgresql'),
  (5900, 'vnc'),
  (8080, 'http-alt'),
  (27017, 'mongodb'),
  (6379, 'redis')
ON CONFLICT (port) DO NOTHING;

-- Вставляем остальные известные порты (well-known: 1-1023)
INSERT INTO well_known_ports (port, name) VALUES
  (1, 'tcpmux'),
  (5, 'rje'),
  (7, 'echo'),
  (9, 'discard'),
  (11, 'systat'),
  (13, 'daytime'),
  (17, 'qotd'),
  (18, 'msp'),
  (19, 'chargen'),
  (37, 'time'),
  (39, 'rlp'),
  (42, 'nameserver'),
  (43, 'nicname'),
  (49, 'tacacs'),
  (50, 're-mail-ck'),
  (51, 'la-maint'),
  (52, 'xns-time'),
  (54, 'xns-ch'),
  (55, 'isi-gl'),
  (56, 'xns-auth'),
  (58, 'xns-mail'),
  (61, 'ni-ftp'),
  (62, 'auditd'),
  (63, 'tacacs-ds'),
  (64, 'bootp'),
  (65, 'tftp'),
  (66, 'gopher'),
  (67, 'dhcp'),
  (68, 'dhcpc'),
  (70, 'gopher'),
  (71, 'netrjs-1'),
  (72, 'netrjs-2'),
  (73, 'netrjs-3'),
  (74, 'netrjs-4'),
  (77, 'priv-rjs'),
  (78, 'deos'),
  (79, 'finger'),
  (81, 'hosts2-ns'),
  (82, 'xfer'),
  (83, 'mit-ml-dev'),
  (84, 'ctf'),
  (85, 'mit-ml-dev'),
  (86, 'mfcobol'),
  (87, 'priv-term-l'),
  (88, 'kerberos'),
  (89, 'su-mit-tg'),
  (90, 'dnsix'),
  (91, 'mit-dov'),
  (92, 'npp'),
  (93, 'dcp'),
  (94, 'objcall'),
  (95, 'supdup'),
  (98, 'linuxconf'),
  (99, 'acme'),
  (101, 'hostname'),
  (102, 'iso-tsap'),
  (103, 'gppitnp'),
  (104, 'acr-nema'),
  (105, 'cso'),
  (106, '3com-tsmux'),
  (107, 'rtelnet'),
  (108, 'snagas'),
  (109, 'pop2'),
  (111, 'rpcbind'),
  (113, 'ident'),
  (115, 'sftp'),
  (117, 'uucp-path'),
  (119, 'nntp'),
  (121, 'erpc'),
  (122, 'smakynet'),
  (125, 'locus-map'),
  (133, 'pwdgen'),
  (134, 'loc-srv'),
  (136, 'profile'),
  (137, 'netbios-ns'),
  (138, 'netbios-dgm'),
  (144, 'news'),
  (146, 'iso-tp0'),
  (147, 'iso-ip'),
  (148, 'jargon'),
  (149, 'aed-512'),
  (150, 'sql-net'),
  (151, 'hems'),
  (152, 'bftp'),
  (153, 'sgmp'),
  (154, 'netsc-prod'),
  (155, 'netsc-dev'),
  (156, 'sqlsrv'),
  (158, 'pcmail-srv'),
  (159, 'nss-routing'),
  (160, 'sgmp-traps'),
  (161, 'snmp'),
  (162, 'snmptrap'),
  (163, 'cmip-man'),
  (164, 'cmip-agent'),
  (166, 'smail'),
  (169, 'send'),
  (170, 'print-srv'),
  (174, 'mailq'),
  (177, 'xdmcp'),
  (178, 'nextstep'),
  (179, 'bgp'),
  (180, 'ris'),
  (183, 'unisys-ssp'),
  (184, 'unisys-elp'),
  (185, 'unisys-als'),
  (186, 'sqlsrv'),
  (188, 'k-shell'),
  (190, 'gacp'),
  (191, 'prospero'),
  (192, 'osu-nms'),
  (193, 'srmp'),
  (194, 'irc'),
  (195, 'dn6-nlm-aud'),
  (196, 'dn6-smm-red'),
  (197, 'dls'),
  (199, 'smux'),
  (200, 'src'),
  (201, 'at-rtmp'),
  (202, 'at-nbp'),
  (203, 'at-echo'),
  (204, 'at-zis'),
  (206, 'z39-50'),
  (209, 'qmtp'),
  (210, 'z39-50'),
  (213, 'ipx'),
  (218, 'mpp'),
  (219, 'uarps'),
  (220, 'imap3'),
  (245, 'link'),
  (347, 'fatserv'),
  (363, 'rsvp_tunnel'),
  (369, 'rpc2portmap'),
  (370, 'codaauth2'),
  (372, 'ulistproc'),
  (389, 'ldap'),
  (427, 'svrloc'),
  (434, 'mobileip-agent'),
  (435, 'mobilip-mn'),
  (444, 'snpp'),
  (448, 'ddm-rdb'),
  (450, 'ddm-dfm'),
  (451, 'ddm-ssl'),
  (452, 'ddm-rdb-ssl'),
  (453, 'ddm-ddm-ssl'),
  (456, 'tram'),
  (464, 'kpasswd'),
  (468, 'photuris'),
  (487, 'saft'),
  (488, 'gss-http'),
  (496, 'pim-rp-disc'),
  (500, 'isakmp'),
  (501, 'stmf'),
  (502, 'asa-appl-proto'),
  (505, 'mailbox-lm'),
  (507, 'crs'),
  (510, 'fcp'),
  (512, 'exec'),
  (513, 'login'),
  (514, 'shell'),
  (515, 'printer'),
  (517, 'talk'),
  (518, 'ntalk'),
  (520, 'efs'),
  (521, 'ripng'),
  (524, 'ncp'),
  (525, 'timed'),
  (526, 'tempo'),
  (530, 'courier'),
  (531, 'conference'),
  (532, 'netnews'),
  (533, 'netwall'),
  (540, 'uucp'),
  (542, 'commerce'),
  (543, 'klogin'),
  (544, 'kshell'),
  (546, 'dhcpv6-client'),
  (547, 'dhcpv6-server'),
  (548, 'afpovertcp'),
  (550, 'new-rwho'),
  (554, 'rtsp'),
  (556, 'remotefs'),
  (560, 'rmonitor'),
  (561, 'monitor'),
  (563, 'nntps'),
  (587, 'submission'),
  (591, 'http-alt'),
  (593, 'http-rpc-epmap'),
  (604, 'tunnel'),
  (631, 'ipp'),
  (636, 'ldaps'),
  (639, 'msdp'),
  (646, 'ldp'),
  (648, 'rrp'),
  (651, 'ieee-mms'),
  (653, 'hello-port'),
  (654, 'repscmd'),
  (655, 'aodv'),
  (656, 'tinc'),
  (657, 'spmp'),
  (658, 'rmc'),
  (660, 'mac-srvr-admin'),
  (661, 'hap'),
  (662, 'pftp'),
  (663, 'purenoise'),
  (664, 'oob-ws-http'),
  (665, 'sun-dr'),
  (666, 'mdqs'),
  (667, 'disclose'),
  (668, 'mecomm'),
  (669, 'meregister'),
  (670, 'vacdsm-sws'),
  (671, 'vacdsm-app'),
  (672, 'vpps-qua'),
  (673, 'cimplex'),
  (674, 'acap'),
  (675, 'dctp'),
  (676, 'vpps-via'),
  (677, 'vpp'),
  (678, 'ggf-ncp'),
  (679, 'mrm'),
  (680, 'entrust-aaas'),
  (681, 'entrust-aams'),
  (682, 'xfr'),
  (683, 'corba-iiop'),
  (684, 'corba-iiop-ssl'),
  (685, 'mdc-portmapper'),
  (686, 'hcp-wismar'),
  (687, 'asipregistry'),
  (688, 'realm-rusd'),
  (689, 'nmap'),
  (690, 'vatp'),
  (691, 'msexch-routing'),
  (692, 'hyperwave-isp'),
  (694, 'ha-cluster'),
  (695, 'ieee-mms-ssl'),
  (696, 'rushd'),
  (697, 'uuidgen'),
  (698, 'olsr'),
  (699, 'accessnetwork'),
  (700, 'epp'),
  (701, 'lmp'),
  (702, 'iris-beep'),
  (706, 'silc'),
  (707, 'scip'),
  (709, 'entrust-kmsh'),
  (710, 'entrust-ash'),
  (711, 'cisco-tdp'),
  (712, 'tbrpf'),
  (749, 'kerberos-adm'),
  (750, 'kerberos-iv'),
  (751, 'kerberos-master'),
  (752, 'passwd-server'),
  (753, 'userreg-server'),
  (754, 'krb-prop'),
  (760, 'krbupdate'),
  (765, 'webster'),
  (767, 'phonebook'),
  (769, 'vid'),
  (770, 'cadlock'),
  (771, 'rtip'),
  (772, 'cycleserv'),
  (773, 'submit'),
  (774, 'rpasswd'),
  (775, 'entomb'),
  (776, 'wpages'),
  (777, 'multiling-http'),
  (780, 'wpgs'),
  (808, 'omirr'),
  (829, 'cert-mgr'),
  (847, 'dhcp-failover2'),
  (848, 'gdoi'),
  (853, 'domain-s'),
  (860, 'iscsi'),
  (861, 'owamp-control'),
  (862, 'twamp-control'),
  (873, 'rsync'),
  (888, 'cddbp'),
  (901, 'swat'),
  (902, 'ideafarm-chat'),
  (903, 'ideafarm-catch'),
  (911, 'xact-backup'),
  (912, 'apex-mesh'),
  (913, 'apex-edge'),
  (989, 'ftps-data'),
  (990, 'ftps'),
  (992, 'telnets'),
  (994, 'ircs'),
  (996, 'icx'),
  (997, 'maitrd'),
  (998, 'busboy'),
  (999, 'garcon'),
  (1000, 'cadlock2'),
  (1001, 'webpush'),
  (1002, 'windows-icfw'),
  (1008, 'udf'),
  (1010, 'surf'),
  (1021, 'exp1'),
  (1022, 'exp2'),
  (1025, 'blackjack'),
  (1026, 'cap'),
  (1027, 'solid-mux'),
  (1028, 'iad1'),
  (1029, 'iad2'),
  (1030, 'iad3'),
  (1031, 'netinfo-local'),
  (1032, 'activesync'),
  (1033, 'mxxrlogin'),
  (1034, 'nsstp'),
  (1035, 'ams'),
  (1036, 'mtqp'),
  (1037, 'sbl'),
  (1038, 'netinfo'),
  (1039, 'rwhois'),
  (1040, 'neod1'),
  (1041, 'neod2'),
  (1042, 'td-postman'),
  (1043, 'blockade-bpsp'),
  (1044, 'epmd'),
  (1045, 'rmiaux'),
  (1046, 'wafs'),
  (1047, 'kingfisher'),
  (1048, 'smsqp'),
  (1049, 'pt2-discover'),
  (1050, 'coauthor'),
  (1051, 'cmd'),
  (1052, 'rtelnetd'),
  (1053, 'dtn-bundle'),
  (1054, 'aspro-vista'),
  (1055, 'an-pcp'),
  (1056, 'vfo'),
  (1057, 'startron'),
  (1058, 'nim'),
  (1059, 'nimreg'),
  (1060, 'polestar'),
  (1061, 'kiosk'),
  (1062, 'veracity'),
  (1063, 'kyoceranetdev'),
  (1064, 'jstel'),
  (1065, 'syscomlan'),
  (1066, 'fpo-fns'),
  (1067, 'instl_bootc'),
  (1068, 'instl_bootp'),
  (1069, 'cognex-insight'),
  (1070, 'gmrp'),
  (1071, 'x-bone-api'),
  (1072, 'bmc-perf-sd'),
  (1073, 'bmc-perf-agent'),
  (1074, 'bmc-perf-mgrd'),
  (1075, 'admind'),
  (1076, 'pov-ray'),
  (1077, 'rscs'),
  (1078, 'snmptren'),
  (1079, 'snmptls-trap'),
  (1080, 'socks'),
  (1081, 'pvuniwien'),
  (1082, 'amt-esd-prot'),
  (1083, 'ansoft-lm-1'),
  (1084, 'ansoft-lm-2'),
  (1085, 'webobjects'),
  (1086, 'cplscrambler-lg'),
  (1087, 'cplscrambler-in'),
  (1088, 'cplscrambler-al'),
  (1089, 'ff-annunc'),
  (1090, 'ff-fms'),
  (1091, 'ff-sm'),
  (1092, 'obrpd'),
  (1093, 'proofd'),
  (1094, 'rootd'),
  (1095, 'nicelink'),
  (1096, 'cnrprotocol'),
  (1097, 'sunclustermgr'),
  (1098, 'rmiactivation'),
  (1099, 'rmiregistry')
ON CONFLICT (port) DO NOTHING;

-- -- Создаем таблицу для известных портов
-- CREATE TABLE IF NOT EXISTS well_known_ports (
--     id INTEGER PRIMARY KEY AUTOINCREMENT,
--     port INTEGER UNIQUE NOT NULL,
--     name TEXT NOT NULL,
--     description TEXT,
--     category TEXT NOT NULL,  -- 'common', 'registered', 'well-known'
--     protocol TEXT DEFAULT 'tcp',  -- 'tcp', 'udp', 'both'
--     created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
-- );

-- -- Создаем индекс для быстрого поиска
-- CREATE INDEX IF NOT EXISTS idx_well_known_ports_port ON well_known_ports(port);
-- CREATE INDEX IF NOT EXISTS idx_well_known_ports_category ON well_known_ports(category);

-- -- Вставляем самые часто используемые порты (common)
-- INSERT INTO well_known_ports (port, name, description, category, protocol) VALUES
--   (20, 'ftp-data', 'FTP Data Transfer', 'common', 'tcp'),
--   (21, 'ftp', 'File Transfer Protocol', 'common', 'tcp'),
--   (22, 'ssh', 'Secure Shell', 'common', 'tcp'),
--   (23, 'telnet', 'Telnet', 'common', 'tcp'),
--   (25, 'smtp', 'Simple Mail Transfer Protocol', 'common', 'tcp'),
--   (53, 'dns', 'Domain Name System', 'common', 'both'),
--   (80, 'http', 'Hypertext Transfer Protocol', 'common', 'tcp'),
--   (110, 'pop3', 'Post Office Protocol v3', 'common', 'tcp'),
--   (123, 'ntp', 'Network Time Protocol', 'common', 'udp'),
--   (135, 'msrpc', 'Microsoft RPC', 'common', 'tcp'),
--   (139, 'netbios-ssn', 'NETBIOS Session Service', 'common', 'tcp'),
--   (143, 'imap', 'Internet Message Access Protocol', 'common', 'tcp'),
--   (443, 'https', 'HTTP Secure', 'common', 'tcp'),
--   (445, 'microsoft-ds', 'Microsoft Directory Services', 'common', 'tcp'),
--   (993, 'imaps', 'IMAP Secure', 'common', 'tcp'),
--   (995, 'pop3s', 'POP3 Secure', 'common', 'tcp'),
--   (1723, 'pptp', 'Point-to-Point Tunneling Protocol', 'common', 'tcp'),
--   (3306, 'mysql', 'MySQL Database', 'common', 'tcp'),
--   (3389, 'rdp', 'Remote Desktop Protocol', 'common', 'tcp'),
--   (5432, 'postgresql', 'PostgreSQL Database', 'common', 'tcp'),
--   (5900, 'vnc', 'Virtual Network Computing', 'common', 'tcp'),
--   (8080, 'http-alt', 'HTTP Alternate', 'common', 'tcp'),
--   (27017, 'mongodb', 'MongoDB Database', 'common', 'tcp'),
--   (6379, 'redis', 'Redis Database', 'common', 'tcp')
-- ON CONFLICT (port) DO NOTHING;

-- -- Вставляем остальные известные порты (well-known: 0-1023)
-- INSERT INTO well_known_ports (port, name, description, category, protocol) VALUES
--   (1, 'tcpmux', 'TCP Port Service Multiplexer', 'well-known', 'tcp'),
--   (5, 'rje', 'Remote Job Entry', 'well-known', 'tcp'),
--   (7, 'echo', 'Echo Protocol', 'well-known', 'both'),
--   (9, 'discard', 'Discard Protocol', 'well-known', 'both'),
--   (11, 'systat', 'Active Users', 'well-known', 'tcp'),
--   (13, 'daytime', 'Daytime Protocol', 'well-known', 'tcp'),
--   (17, 'qotd', 'Quote of the Day', 'well-known', 'tcp'),
--   (18, 'msp', 'Message Send Protocol', 'well-known', 'tcp'),
--   (19, 'chargen', 'Character Generator Protocol', 'well-known', 'both'),
--   (37, 'time', 'Time Protocol', 'well-known', 'tcp'),
--   (39, 'rlp', 'Resource Location Protocol', 'well-known', 'tcp'),
--   (42, 'nameserver', 'Host Name Server', 'well-known', 'tcp'),
--   (43, 'nicname', 'Whois Protocol', 'well-known', 'tcp'),
--   (49, 'tacacs', 'TAC Access Control System', 'well-known', 'tcp'),
--   (50, 're-mail-ck', 'Remote Mail Checking Protocol', 'well-known', 'tcp'),
--   (51, 'la-maint', 'IMP Logical Address Maintenance', 'well-known', 'tcp'),
--   (52, 'xns-time', 'XNS Time Protocol', 'well-known', 'tcp'),
--   (54, 'xns-ch', 'XNS Clearinghouse', 'well-known', 'tcp'),
--   (55, 'isi-gl', 'ISI Graphics Language', 'well-known', 'tcp'),
--   (56, 'xns-auth', 'XNS Authentication', 'well-known', 'tcp'),
--   (58, 'xns-mail', 'XNS Mail', 'well-known', 'tcp'),
--   (61, 'ni-ftp', 'NI FTP', 'well-known', 'tcp'),
--   (62, 'auditd', 'Audit Daemon', 'well-known', 'tcp'),
--   (63, 'tacacs-ds', 'TACACS-Database Service', 'well-known', 'tcp'),
--   (64, 'bootp', 'Bootstrap Protocol Server', 'well-known', 'udp'),
--   (65, 'tftp', 'Trivial File Transfer Protocol', 'well-known', 'udp'),
--   (66, 'gopher', 'Gopher Protocol', 'well-known', 'tcp'),
--   (67, 'dhcp', 'DHCP Server', 'well-known', 'udp'),
--   (68, 'dhcpc', 'DHCP Client', 'well-known', 'udp'),
--   (69, 'tftp', 'Trivial File Transfer Protocol', 'well-known', 'udp'),
--   (70, 'gopher', 'Gopher Protocol', 'well-known', 'tcp'),
--   (71, 'netrjs-1', 'Remote Job Service', 'well-known', 'tcp'),
--   (72, 'netrjs-2', 'Remote Job Service', 'well-known', 'tcp'),
--   (73, 'netrjs-3', 'Remote Job Service', 'well-known', 'tcp'),
--   (74, 'netrjs-4', 'Remote Job Service', 'well-known', 'tcp'),
--   (77, 'priv-rjs', 'Private Remote Job Service', 'well-known', 'tcp'),
--   (78, 'deos', 'Distributed External Object Store', 'well-known', 'tcp'),
--   (79, 'finger', 'Finger Protocol', 'well-known', 'tcp'),
--   (81, 'hosts2-ns', 'HOSTS2 Name Server', 'well-known', 'tcp'),
--   (82, 'xfer', 'XFER Utility', 'well-known', 'tcp'),
--   (83, 'mit-ml-dev', 'MIT ML Device', 'well-known', 'tcp'),
--   (84, 'ctf', 'Common Trace Facility', 'well-known', 'tcp'),
--   (85, 'mit-ml-dev', 'MIT ML Device', 'well-known', 'tcp'),
--   (86, 'mfcobol', 'Micro Focus Cobol', 'well-known', 'tcp'),
--   (87, 'priv-term-l', 'Private Terminal Link', 'well-known', 'tcp'),
--   (88, 'kerberos', 'Kerberos', 'well-known', 'tcp'),
--   (89, 'su-mit-tg', 'SU/MIT Telnet Gateway', 'well-known', 'tcp'),
--   (90, 'dnsix', 'DNSIX Securit Attribute Token Map', 'well-known', 'tcp'),
--   (91, 'mit-dov', 'MIT Dover Spooler', 'well-known', 'tcp'),
--   (92, 'npp', 'Network Printing Protocol', 'well-known', 'tcp'),
--   (93, 'dcp', 'Device Control Protocol', 'well-known', 'tcp'),
--   (94, 'objcall', 'Tivoli Object Dispatcher', 'well-known', 'tcp'),
--   (95, 'supdup', 'SUPDUP Protocol', 'well-known', 'tcp'),
--   (98, 'linuxconf', 'Linuxconf', 'well-known', 'tcp'),
--   (99, 'acme', 'ACME Remote Management', 'well-known', 'tcp'),
--   (101, 'hostname', 'NIC Host Name Server', 'well-known', 'tcp'),
--   (102, 'iso-tsap', 'ISO-TSAP Class 0', 'well-known', 'tcp'),
--   (103, 'gppitnp', 'Genesis Point-to-Point Trans Net', 'well-known', 'tcp'),
--   (104, 'acr-nema', 'ACR-NEMA Digital Imag. & Comm. 300', 'well-known', 'tcp'),
--   (105, 'cso', 'CCSO name server protocol', 'well-known', 'tcp'),
--   (106, '3com-tsmux', '3COM-TSMUX', 'well-known', 'tcp'),
--   (107, 'rtelnet', 'Remote Telnet Service', 'well-known', 'tcp'),
--   (108, 'snagas', 'SNA Gateway Access Server', 'well-known', 'tcp'),
--   (109, 'pop2', 'Post Office Protocol - Version 2', 'well-known', 'tcp'),
--   (111, 'rpcbind', 'SUN Remote Procedure Call', 'well-known', 'tcp'),
--   (113, 'ident', 'Ident Protocol', 'well-known', 'tcp'),
--   (115, 'sftp', 'Simple File Transfer Protocol', 'well-known', 'tcp'),
--   (117, 'uucp-path', 'UUCP Path Service', 'well-known', 'tcp'),
--   (119, 'nntp', 'Network News Transfer Protocol', 'well-known', 'tcp'),
--   (121, 'erpc', 'Encore Expedited Remote Pro.Call', 'well-known', 'tcp'),
--   (122, 'smakynet', 'SMAKY Net Protocol', 'well-known', 'tcp'),
--   (125, 'locus-map', 'Locus PC-Interface Net Map Ser', 'well-known', 'tcp'),
--   (133, 'pwdgen', 'Password Generator Protocol', 'well-known', 'tcp'),
--   (134, 'loc-srv', 'Location Service', 'well-known', 'tcp'),
--   (136, 'profile', 'Profile Naming System', 'well-known', 'tcp'),
--   (137, 'netbios-ns', 'NETBIOS Name Service', 'well-known', 'tcp'),
--   (138, 'netbios-dgm', 'NETBIOS Datagram Service', 'well-known', 'tcp'),
--   (144, 'news', 'Network News Transfer Protocol', 'well-known', 'tcp'),
--   (146, 'iso-tp0', 'ISO-IP0', 'well-known', 'tcp'),
--   (147, 'iso-ip', 'ISO-IP', 'well-known', 'tcp'),
--   (148, 'jargon', 'Jargon', 'well-known', 'tcp'),
--   (149, 'aed-512', 'AED 512 Emulation Service', 'well-known', 'tcp'),
--   (150, 'sql-net', 'SQL-NET', 'well-known', 'tcp'),
--   (151, 'hems', 'HEMS', 'well-known', 'tcp'),
--   (152, 'bftp', 'Background File Transfer Program', 'well-known', 'tcp'),
--   (153, 'sgmp', 'SGMP', 'well-known', 'tcp'),
--   (154, 'netsc-prod', 'NETSC', 'well-known', 'tcp'),
--   (155, 'netsc-dev', 'NETSC', 'well-known', 'tcp'),
--   (156, 'sqlsrv', 'SQL Service', 'well-known', 'tcp'),
--   (158, 'pcmail-srv', 'PCMail Server', 'well-known', 'tcp'),
--   (159, 'nss-routing', 'NSS-Routing', 'well-known', 'tcp'),
--   (160, 'sgmp-traps', 'SGMP-TRAPS', 'well-known', 'tcp'),
--   (161, 'snmp', 'Simple Network Management Protocol', 'well-known', 'udp'),
--   (162, 'snmptrap', 'SNMP Trap', 'well-known', 'udp'),
--   (163, 'cmip-man', 'CMIP/TCP Manager', 'well-known', 'tcp'),
--   (164, 'cmip-agent', 'CMIP/TCP Agent', 'well-known', 'tcp'),
--   (166, 'smail', 'smail', 'well-known', 'tcp'),
--   (169, 'send', 'Send Protocol', 'well-known', 'tcp'),
--   (170, 'print-srv', 'Network PostScript', 'well-known', 'tcp'),
--   (174, 'mailq', 'MAILQ', 'well-known', 'tcp'),
--   (177, 'xdmcp', 'X Display Manager Control Protocol', 'well-known', 'udp'),
--   (178, 'nextstep', 'NeXTStep Window Server', 'well-known', 'tcp'),
--   (179, 'bgp', 'Border Gateway Protocol', 'well-known', 'tcp'),
--   (180, 'ris', 'Intergraph', 'well-known', 'tcp'),
--   (183, 'unisys-ssp', 'Unisys NSS', 'well-known', 'tcp'),
--   (184, 'unisys-elp', 'Unisys ELPS', 'well-known', 'tcp'),
--   (185, 'unisys-als', 'Unisys Audit Srv', 'well-known', 'tcp'),
--   (186, 'sqlsrv', 'Oracle SQL*Net', 'well-known', 'tcp'),
--   (188, 'k-shell', 'K-Shell', 'well-known', 'tcp'),
--   (190, 'gacp', 'Gateway Access Control Protocol', 'well-known', 'tcp'),
--   (191, 'prospero', 'Prospero Directory Service', 'well-known', 'tcp'),
--   (192, 'osu-nms', 'OSU Network Monitoring System', 'well-known', 'tcp'),
--   (193, 'srmp', 'Spider Remote Monitoring Protocol', 'well-known', 'tcp'),
--   (194, 'irc', 'Internet Relay Chat Protocol', 'well-known', 'tcp'),
--   (195, 'dn6-nlm-aud', 'DN6 NLM Audit', 'well-known', 'tcp'),
--   (196, 'dn6-smm-red', 'DN6 SMM Red', 'well-known', 'tcp'),
--   (197, 'dls', 'Directory Location Service', 'well-known', 'tcp'),
--   (199, 'smux', 'SMUX', 'well-known', 'tcp'),
--   (200, 'src', 'IBM System Resource Controller', 'well-known', 'tcp'),
--   (201, 'at-rtmp', 'AppleTalk Routing Maintenance', 'well-known', 'tcp'),
--   (202, 'at-nbp', 'AppleTalk Name Binding', 'well-known', 'tcp'),
--   (203, 'at-echo', 'AppleTalk Echo', 'well-known', 'tcp'),
--   (204, 'at-zis', 'AppleTalk Zone Information', 'well-known', 'tcp'),
--   (206, 'z39-50', 'ANSI Z39.50', 'well-known', 'tcp'),
--   (209, 'qmtp', 'Quick Mail Transfer Protocol', 'well-known', 'tcp'),
--   (210, 'z39-50', 'ANSI Z39.50', 'well-known', 'tcp'),
--   (213, 'ipx', 'IPX', 'well-known', 'udp'),
--   (218, 'mpp', 'Message Posting Protocol', 'well-known', 'tcp'),
--   (219, 'uarps', 'Universal Address Resolution Protocol', 'well-known', 'tcp'),
--   (220, 'imap3', 'Interactive Mail Access Protocol v3', 'well-known', 'tcp'),
--   (245, 'link', 'LINK', 'well-known', 'udp'),
--   (347, 'fatserv', 'FATMEN Server', 'well-known', 'tcp'),
--   (363, 'rsvp_tunnel', 'RSVP Tunnel', 'well-known', 'tcp'),
--   (369, 'rpc2portmap', 'RPC2PORTMAP', 'well-known', 'tcp'),
--   (370, 'codaauth2', 'CODAAUTH2', 'well-known', 'tcp'),
--   (372, 'ulistproc', 'ListProcessor', 'well-known', 'tcp'),
--   (389, 'ldap', 'Lightweight Directory Access Protocol', 'well-known', 'tcp'),
--   (427, 'svrloc', 'Server Location', 'well-known', 'tcp'),
--   (434, 'mobileip-agent', 'MobileIP-Agent', 'well-known', 'udp'),
--   (435, 'mobilip-mn', 'MobilIP-MN', 'well-known', 'udp'),
--   (444, 'snpp', 'Simple Network Paging Protocol', 'well-known', 'tcp'),
--   (448, 'ddm-rdb', 'DDM-RDB', 'well-known', 'tcp'),
--   (450, 'ddm-dfm', 'DDM-DFM', 'well-known', 'tcp'),
--   (451, 'ddm-ssl', 'DDM-SSL', 'well-known', 'tcp'),
--   (452, 'ddm-rdb-ssl', 'DDM-RDB-SSL', 'well-known', 'tcp'),
--   (453, 'ddm-ddm-ssl', 'DDM-DDM-SSL', 'well-known', 'tcp'),
--   (456, 'tram', 'TRAM', 'well-known', 'udp'),
--   (464, 'kpasswd', 'Kerberos Password Change', 'well-known', 'tcp'),
--   (468, 'photuris', 'Photuris', 'well-known', 'udp'),
--   (487, 'saft', 'Simple Asynchronous File Transfer', 'well-known', 'tcp'),
--   (488, 'gss-http', 'GSS HTTP', 'well-known', 'tcp'),
--   (496, 'pim-rp-disc', 'PIM-RP-DISC', 'well-known', 'udp'),
--   (500, 'isakmp', 'ISAKMP', 'well-known', 'udp'),
--   (501, 'stmf', 'STMF', 'well-known', 'tcp'),
--   (502, 'asa-appl-proto', 'ASA Appl Protocol', 'well-known', 'tcp'),
--   (505, 'mailbox-lm', 'Mailbox-LM', 'well-known', 'tcp'),
--   (507, 'crs', 'CRS', 'well-known', 'tcp'),
--   (510, 'fcp', 'FirstClass Protocol', 'well-known', 'tcp'),
--   (512, 'exec', 'Remote Process Execution', 'well-known', 'tcp'),
--   (513, 'login', 'Remote Login', 'well-known', 'tcp'),
--   (514, 'shell', 'Remote Shell', 'well-known', 'tcp'),
--   (515, 'printer', 'Line Printer Daemon', 'well-known', 'tcp'),
--   (517, 'talk', 'Talk', 'well-known', 'udp'),
--   (518, 'ntalk', 'NTalk', 'well-known', 'udp'),
--   (520, 'efs', 'Extended File System', 'well-known', 'tcp'),
--   (521, 'ripng', 'RIPng', 'well-known', 'udp'),
--   (524, 'ncp', 'NCP', 'well-known', 'tcp'),
--   (525, 'timed', 'Timeserver', 'well-known', 'udp'),
--   (526, 'tempo', 'Tempo', 'well-known', 'tcp'),
--   (530, 'courier', 'Courier', 'well-known', 'tcp'),
--   (531, 'conference', 'Chat', 'well-known', 'tcp'),
--   (532, 'netnews', 'Readnews', 'well-known', 'tcp'),
--   (533, 'netwall', 'For emergency broadcasts', 'well-known', 'udp'),
--   (540, 'uucp', 'UUCP', 'well-known', 'tcp'),
--   (542, 'commerce', 'Commercial', 'well-known', 'tcp'),
--   (543, 'klogin', 'Kerberos Login', 'well-known', 'tcp'),
--   (544, 'kshell', 'Kerberos Shell', 'well-known', 'tcp'),
--   (546, 'dhcpv6-client', 'DHCPv6 Client', 'well-known', 'udp'),
--   (547, 'dhcpv6-server', 'DHCPv6 Server', 'well-known', 'udp'),
--   (548, 'afpovertcp', 'AFP over TCP', 'well-known', 'tcp'),
--   (550, 'new-rwho', 'New RWHO', 'well-known', 'udp'),
--   (554, 'rtsp', 'Real Time Stream Control Protocol', 'well-known', 'tcp'),
--   (556, 'remotefs', 'Remotefs', 'well-known', 'tcp'),
--   (560, 'rmonitor', 'RMONITOR', 'well-known', 'udp'),
--   (561, 'monitor', 'MONITOR', 'well-known', 'udp'),
--   (563, 'nntps', 'NNTP over SSL', 'well-known', 'tcp'),
--   (587, 'submission', 'Submission', 'well-known', 'tcp'),
--   (591, 'http-alt', 'FileMaker HTTP Alternate', 'well-known', 'tcp'),
--   (593, 'http-rpc-epmap', 'HTTP RPC Ep Map', 'well-known', 'tcp'),
--   (604, 'tunnel', 'TUNNEL', 'well-known', 'tcp'),
--   (631, 'ipp', 'Internet Printing Protocol', 'well-known', 'tcp'),
--   (636, 'ldaps', 'LDAP over SSL', 'well-known', 'tcp'),
--   (639, 'msdp', 'MSDP', 'well-known', 'tcp'),
--   (646, 'ldp', 'LDP', 'well-known', 'tcp'),
--   (648, 'rrp', 'Registry Registrar Protocol', 'well-known', 'tcp'),
--   (651, 'ieee-mms', 'IEEE MMS', 'well-known', 'tcp'),
--   (653, 'hello-port', 'HELLO PORT', 'well-known', 'tcp'),
--   (654, 'repscmd', 'RepCmd', 'well-known', 'tcp'),
--   (655, 'aodv', 'AODV', 'well-known', 'udp'),
--   (656, 'tinc', 'TINC', 'well-known', 'tcp'),
--   (657, 'spmp', 'SPMP', 'well-known', 'tcp'),
--   (658, 'rmc', 'RMC', 'well-known', 'tcp'),
--   (660, 'mac-srvr-admin', 'MacOS Server Admin', 'well-known', 'tcp'),
--   (661, 'hap', 'HAP', 'well-known', 'tcp'),
--   (662, 'pftp', 'PFTP', 'well-known', 'tcp'),
--   (663, 'purenoise', 'PureNoise', 'well-known', 'tcp'),
--   (664, 'oob-ws-http', 'OOB WS HTTP', 'well-known', 'tcp'),
--   (665, 'sun-dr', 'SUN DR', 'well-known', 'tcp'),
--   (666, 'mdqs', 'MDQS', 'well-known', 'tcp'),
--   (667, 'disclose', 'Campaign Contribution Disclosure', 'well-known', 'tcp'),
--   (668, 'mecomm', 'MeComm', 'well-known', 'tcp'),
--   (669, 'meregister', 'MeRegister', 'well-known', 'tcp'),
--   (670, 'vacdsm-sws', 'VACDSM-SWS', 'well-known', 'tcp'),
--   (671, 'vacdsm-app', 'VACDSM-APP', 'well-known', 'tcp'),
--   (672, 'vpps-qua', 'VPPS-QUA', 'well-known', 'tcp'),
--   (673, 'cimplex', 'CIMPLEX', 'well-known', 'tcp'),
--   (674, 'acap', 'ACAP', 'well-known', 'tcp'),
--   (675, 'dctp', 'DCTP', 'well-known', 'tcp'),
--   (676, 'vpps-via', 'VPPS Via', 'well-known', 'tcp'),
--   (677, 'vpp', 'VPP', 'well-known', 'tcp'),
--   (678, 'ggf-ncp', 'GGF NCP', 'well-known', 'tcp'),
--   (679, 'mrm', 'MRM', 'well-known', 'tcp'),
--   (680, 'entrust-aaas', 'Entrust AAAS', 'well-known', 'tcp'),
--   (681, 'entrust-aams', 'Entrust AAMS', 'well-known', 'tcp'),
--   (682, 'xfr', 'XFR', 'well-known', 'tcp'),
--   (683, 'corba-iiop', 'CORBA IIOP', 'well-known', 'tcp'),
--   (684, 'corba-iiop-ssl', 'CORBA IIOP SSL', 'well-known', 'tcp'),
--   (685, 'mdc-portmapper', 'MDC Port Mapper', 'well-known', 'tcp'),
--   (686, 'hcp-wismar', 'HCP Wismar', 'well-known', 'tcp'),
--   (687, 'asipregistry', 'ASIP Registry', 'well-known', 'tcp'),
--   (688, 'realm-rusd', 'ApplianceWare Managment', 'well-known', 'tcp'),
--   (689, 'nmap', 'NMAP', 'well-known', 'tcp'),
--   (690, 'vatp', 'VATP', 'well-known', 'tcp'),
--   (691, 'msexch-routing', 'MS Exchange Routing', 'well-known', 'tcp'),
--   (692, 'hyperwave-isp', 'Hyperwave ISP', 'well-known', 'tcp'),
--   (694, 'ha-cluster', 'HA Cluster', 'well-known', 'tcp'),
--   (695, 'ieee-mms-ssl', 'IEEE MMS SSL', 'well-known', 'tcp'),
--   (696, 'rushd', 'RUSHD', 'well-known', 'tcp'),
--   (697, 'uuidgen', 'UUIDGEN', 'well-known', 'tcp'),
--   (698, 'olsr', 'OLSR', 'well-known', 'udp'),
--   (699, 'accessnetwork', 'Access Network', 'well-known', 'tcp'),
--   (700, 'epp', 'Extensible Provisioning Protocol', 'well-known', 'tcp'),
--   (701, 'lmp', 'Link Management Protocol', 'well-known', 'tcp'),
--   (702, 'iris-beep', 'IRIS over BEEP', 'well-known', 'tcp'),
--   (706, 'silc', 'SILC', 'well-known', 'tcp'),
--   (707, 'scip', 'SCIP', 'well-known', 'tcp'),
--   (709, 'entrust-kmsh', 'Entrust Key Management Service Handler', 'well-known', 'tcp'),
--   (710, 'entrust-ash', 'Entrust Administration Service Handler', 'well-known', 'tcp'),
--   (711, 'cisco-tdp', 'Cisco TDP', 'well-known', 'tcp'),
--   (712, 'tbrpf', 'TBRPF', 'well-known', 'udp'),
--   (749, 'kerberos-adm', 'Kerberos Administration', 'well-known', 'tcp'),
--   (750, 'kerberos-iv', 'Kerberos Version IV', 'well-known', 'tcp'),
--   (751, 'kerberos-master', 'Kerberos Master', 'well-known', 'tcp'),
--   (752, 'passwd-server', 'Password Server', 'well-known', 'tcp'),
--   (753, 'userreg-server', 'User Registration Server', 'well-known', 'tcp'),
--   (754, 'krb-prop', 'Kerberos Propagation', 'well-known', 'tcp'),
--   (760, 'krbupdate', 'Kerberos Update', 'well-known', 'tcp'),
--   (765, 'webster', 'Webster', 'well-known', 'tcp'),
--   (767, 'phonebook', 'Phonebook', 'well-known', 'tcp'),
--   (769, 'vid', 'Vid', 'well-known', 'tcp'),
--   (770, 'cadlock', 'Cadlock', 'well-known', 'tcp'),
--   (771, 'rtip', 'RTIP', 'well-known', 'tcp'),
--   (772, 'cycleserv', 'CycleServ', 'well-known', 'tcp'),
--   (773, 'submit', 'Submit', 'well-known', 'tcp'),
--   (774, 'rpasswd', 'Rpasswd', 'well-known', 'tcp'),
--   (775, 'entomb', 'Entomb', 'well-known', 'tcp'),
--   (776, 'wpages', 'WPages', 'well-known', 'tcp'),
--   (777, 'multiling-http', 'Multiling HTTP', 'well-known', 'tcp'),
--   (780, 'wpgs', 'WPGS', 'well-known', 'tcp'),
--   (808, 'omirr', 'OmniRIR', 'well-known', 'tcp'),
--   (829, 'cert-mgr', 'Certificate Management', 'well-known', 'tcp'),
--   (847, 'dhcp-failover2', 'DHCP Failover 2', 'well-known', 'tcp'),
--   (848, 'gdoi', 'Group Domain of Interpretation', 'well-known', 'tcp'),
--   (853, 'domain-s', 'DNS over TLS', 'well-known', 'tcp'),
--   (860, 'iscsi', 'iSCSI', 'well-known', 'tcp'),
--   (861, 'owamp-control', 'OWAMP-Control', 'well-known', 'tcp'),
--   (862, 'twamp-control', 'TWAMP-Control', 'well-known', 'tcp'),
--   (873, 'rsync', 'rsync', 'well-known', 'tcp'),
--   (888, 'cddbp', 'CDDBP', 'well-known', 'tcp'),
--   (901, 'swat', 'SWAT', 'well-known', 'tcp'),
--   (902, 'ideafarm-chat', 'IdeaFarm Chat', 'well-known', 'tcp'),
--   (903, 'ideafarm-catch', 'IdeaFarm Catch', 'well-known', 'tcp'),
--   (911, 'xact-backup', 'XACT Backup', 'well-known', 'tcp'),
--   (912, 'apex-mesh', 'APEX Mesh', 'well-known', 'tcp'),
--   (913, 'apex-edge', 'APEX Edge', 'well-known', 'tcp'),
--   (989, 'ftps-data', 'FTP over TLS/SSL (data)', 'well-known', 'tcp'),
--   (990, 'ftps', 'FTP over TLS/SSL (control)', 'well-known', 'tcp'),
--   (992, 'telnets', 'Telnet over TLS/SSL', 'well-known', 'tcp'),
--   (994, 'ircs', 'IRC over TLS/SSL', 'well-known', 'tcp'),
--   (996, 'icx', 'ICX', 'well-known', 'tcp'),
--   (997, 'maitrd', 'Maitrd', 'well-known', 'tcp'),
--   (998, 'busboy', 'Busboy', 'well-known', 'tcp'),
--   (999, 'garcon', 'Garcon', 'well-known', 'tcp'),
--   (1000, 'cadlock2', 'Cadlock2', 'well-known', 'tcp'),
--   (1001, 'webpush', 'WebPush', 'well-known', 'tcp'),
--   (1002, 'windows-icfw', 'Windows ICFW', 'well-known', 'tcp'),
--   (1008, 'udf', 'UDF', 'well-known', 'tcp'),
--   (1010, 'surf', 'Surf', 'well-known', 'tcp'),
--   (1021, 'exp1', 'RFC3692-style Experiment 1', 'well-known', 'tcp'),
--   (1022, 'exp2', 'RFC3692-style Experiment 2', 'well-known', 'tcp'),
--   (1025, 'blackjack', 'Blackjack', 'well-known', 'tcp'),
--   (1026, 'cap', 'Calendar Access Protocol', 'well-known', 'tcp'),
--   (1027, 'solid-mux', 'Solid Mux', 'well-known', 'tcp'),
--   (1028, 'iad1', 'Invisible IRC Proxy', 'well-known', 'tcp'),
--   (1029, 'iad2', 'Invisible IRC Proxy', 'well-known', 'tcp'),
--   (1030, 'iad3', 'Invisible IRC Proxy', 'well-known', 'tcp'),
--   (1031, 'netinfo-local', 'NetInfo Local', 'well-known', 'tcp'),
--   (1032, 'activesync', 'ActiveSync', 'well-known', 'tcp'),
--   (1033, 'mxxrlogin', 'MX-XR Login', 'well-known', 'tcp'),
--   (1034, 'nsstp', 'NSSTP', 'well-known', 'tcp'),
--   (1035, 'ams', 'AMS', 'well-known', 'tcp'),
--   (1036, 'mtqp', 'MTQP', 'well-known', 'tcp'),
--   (1037, 'sbl', 'SBL', 'well-known', 'tcp'),
--   (1038, 'netinfo', 'NetInfo', 'well-known', 'tcp'),
--   (1039, 'rwhois', 'RWhois', 'well-known', 'tcp'),
--   (1040, 'neod1', 'NeoD1', 'well-known', 'tcp'),
--   (1041, 'neod2', 'NeoD2', 'well-known', 'tcp'),
--   (1042, 'td-postman', 'Tobit David Postman VPMN', 'well-known', 'tcp'),
--   (1043, 'blockade-bpsp', 'Blockade BPSP', 'well-known', 'tcp'),
--   (1044, 'epmd', 'Erlang Port Mapper Daemon', 'well-known', 'tcp'),
--   (1045, 'rmiaux', 'RMI Activation', 'well-known', 'tcp'),
--   (1046, 'wafs', 'Workflow Automation Service', 'well-known', 'tcp'),
--   (1047, 'kingfisher', 'Kingfisher', 'well-known', 'tcp'),
--   (1048, 'smsqp', 'SMSQP', 'well-known', 'tcp'),
--   (1049, 'pt2-discover', 'PT2-DISCOVER', 'well-known', 'tcp'),
--   (1050, 'coauthor', 'COAUTHOR', 'well-known', 'tcp'),
--   (1051, 'cmd', 'CMD', 'well-known', 'tcp'),
--   (1052, 'rtelnetd', 'RTELNETD', 'well-known', 'tcp'),
--   (1053, 'dtn-bundle', 'DTN Bundle', 'well-known', 'tcp'),
--   (1054, 'aspro-vista', 'Aspro-Vista', 'well-known', 'tcp'),
--   (1055, 'an-pcp', 'AN-PCP', 'well-known', 'tcp'),
--   (1056, 'vfo', 'VFO', 'well-known', 'tcp'),
--   (1057, 'startron', 'STARTRON', 'well-known', 'tcp'),
--   (1058, 'nim', 'NIM', 'well-known', 'tcp'),
--   (1059, 'nimreg', 'NIMREG', 'well-known', 'tcp'),
--   (1060, 'polestar', 'POLESTAR', 'well-known', 'tcp'),
--   (1061, 'kiosk', 'KIOSK', 'well-known', 'tcp'),
--   (1062, 'veracity', 'Veracity', 'well-known', 'tcp'),
--   (1063, 'kyoceranetdev', 'KyoceraNetDev', 'well-known', 'tcp'),
--   (1064, 'jstel', 'JStel', 'well-known', 'tcp'),
--   (1065, 'syscomlan', 'SYSCOMLAN', 'well-known', 'tcp'),
--   (1066, 'fpo-fns', 'FPO-FNS', 'well-known', 'tcp'),
--   (1067, 'instl_bootc', 'Installation Bootstrap Proto. Serv.', 'well-known', 'udp'),
--   (1068, 'instl_bootp', 'Installation Bootstrap Proto. Cli.', 'well-known', 'udp'),
--   (1069, 'cognex-insight', 'COGNEX-INSIGHT', 'well-known', 'tcp'),
--   (1070, 'gmrp', 'GMRP', 'well-known', 'tcp'),
--   (1071, 'x-bone-api', 'X-Bone API', 'well-known', 'tcp'),
--   (1072, 'bmc-perf-sd', 'BMC-PERFORM-SERVICE DAEMON', 'well-known', 'tcp'),
--   (1073, 'bmc-perf-agent', 'BMC General PERFORM Agent', 'well-known', 'tcp'),
--   (1074, 'bmc-perf-mgrd', 'BMC-PERFORM-MANAGER DAEMON', 'well-known', 'tcp'),
--   (1075, 'admind', 'Admind', 'well-known', 'tcp'),
--   (1076, 'pov-ray', 'POV-Ray', 'well-known', 'tcp'),
--   (1077, 'rscs', 'RSCS', 'well-known', 'tcp'),
--   (1078, 'snmptren', 'SNMP-TLS', 'well-known', 'tcp'),
--   (1079, 'snmptls-trap', 'SNMP-TLS-TRAP', 'well-known', 'tcp'),
--   (1080, 'socks', 'SOCKS Proxy', 'well-known', 'tcp'),
--   (1081, 'pvuniwien', 'PVUNIWIEN', 'well-known', 'tcp'),
--   (1082, 'amt-esd-prot', 'AMT-ESD-PROT', 'well-known', 'tcp'),
--   (1083, 'ansoft-lm-1', 'Anasoft License Manager', 'well-known', 'tcp'),
--   (1084, 'ansoft-lm-2', 'Anasoft License Manager', 'well-known', 'tcp'),
--   (1085, 'webobjects', 'WebObjects', 'well-known', 'tcp'),
--   (1086, 'cplscrambler-lg', 'CPL Scrambler Logging', 'well-known', 'tcp'),
--   (1087, 'cplscrambler-in', 'CPL Scrambler Internal', 'well-known', 'tcp'),
--   (1088, 'cplscrambler-al', 'CPL Scrambler Alarm Log', 'well-known', 'tcp'),
--   (1089, 'ff-annunc', 'FF Annunciation', 'well-known', 'tcp'),
--   (1090, 'ff-fms', 'FF Fieldbus Message Specification', 'well-known', 'tcp'),
--   (1091, 'ff-sm', 'FF System Management', 'well-known', 'tcp'),
--   (1092, 'obrpd', 'Open Business Reporting Protocol', 'well-known', 'tcp'),
--   (1093, 'proofd', 'PROOFD', 'well-known', 'tcp'),
--   (1094, 'rootd', 'ROOTD', 'well-known', 'tcp'),
--   (1095, 'nicelink', 'NICELink', 'well-known', 'tcp'),
--   (1096, 'cnrprotocol', 'Common Name Resolution Protocol', 'well-known', 'tcp'),
--   (1097, 'sunclustermgr', 'Sun Cluster Manager', 'well-known', 'tcp'),
--   (1098, 'rmiactivation', 'RMI Activation', 'well-known', 'tcp'),
--   (1099, 'rmiregistry', 'RMI Registry', 'well-known', 'tcp')
-- ON CONFLICT (port) DO NOTHING;